server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes: #Конкретизируем какой микросервис обрабатывает
        - id: test
          uri: lb://e-client
          predicates:
            - Path=/test/main
            - Method=GET

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka